### ISSUE TITLE
New name - new life

### ISSUE THREAD

**Issue by AlexMost** [ttag-org/ttag#105]
Issue - https://github.com/c-3po-org/c-3po/issues/104
So we need to decide how we should rename this project, to avoid legal infringement. 

My thoughts about the new name (can be discussed here also):

* short (3 - 5 characters).
* does not contain translation, localization, i18n in its name.
* there should be no existing trademark with that name.
* available package name on the npm.

Feel free to suggest your ideas @MrOrz @vharitonsky @alxpy @erickwilder

**Comment by alxpy** [comment]
owlf

**Comment by erickwilder** [comment]
@alxpy What is the reasoning behind this name choice?

After thinking a little I came up with `ttag` as my first suggestion. 

#### Rationale:
The library is defined as _Modern javascript i18n localization library based on es6 **tagged** templates and the good old GNU gettext_. It also makes use of the `t` tag to mark translatable text. I usually prefer names that put function ahead of style (e.g: `webpack`: the name clearly demonstrate the intents of the package  vs `grunt` which requires a bit of explanation about what the tool actually does)

It also makes things compact when thinking about its design and usability by third party projects:

```javascript
import {t, ngettext, msgid} from 'ttag'
``` 

And finally, it respects the rule established by @AlexMost 😄 

---

ℹ️ Further research for possible trademarks has to be made but so far I couldn't find any blockers.

**Comment by AlexMost** [comment]
@erickwilder nice suggestion. @alxpy, @MrOrz what do you think?

**Comment by erickwilder** [comment]
Any other suggestions?

**Comment by AlexMost** [comment]
@erickwilder I think `ttag` is good, we can take that one. So, basically now we need:

1. Create new github org + repository.
2. Fix docs.
3. Create npm packages.
4. Fix docs.
5. Register and use new domain `ttag.js.org` for the project's main page.

**Comment by erickwilder** [comment]
Okay, I can start working on patching the docs (and perhaps patching any npm publishing scripts). 

All the rest I think is better if the current repo owners take care of.

---

Side note: I really liked @MrOrz idea for the logo. What about making everything based on open source and use some openclipart.org's assets for that?

I've found this one quite good for a starting point. 
https://openclipart.org/detail/293011/tea-bag-in-cactus-cowboy-bold-stroke-icon-style

Since _remixes_ are allowed we might play a bit with colors (or not)

**Comment by AlexMost** [comment]
@erickwilder sounds great. Sorry for the delayed responses, currently I am a little bit overloaded at work... If you have a chance to help with docs I will really appreciate. I have already reserved `ttag` package on npm - https://www.npmjs.com/package/ttag. Hope will have more time in the next week to close this issue.

**Comment by erickwilder** [comment]
It would be nice to reserve`babel-plugin-ttag` on NPM as well.

**Comment by erickwilder** [comment]
@AlexMost 

I've been thinking a little about the transition process from the old to the new name and it would be good (for anyone using the library/babel plugin) to start warning users that a future change will be backward incompatible. For that I thought about the following:

1. Add a section to the documentation instructing users how to proceed with the migration from `c-3po` to `ttag`; as far I  can think of this will include: installing the new `npm` packages, replacing imports from `c-3po` to `ttag` and nothing more than that. If I'm missing something, we can always patch it 😄 
2. Release ASAP a _patch version_ including a warning to state that the library will be deprecated in favor of the new name; this warning should include a link to the article described above.
3. After publishing the new npm package, release a minor version to the current package on NPM adding deprecation warnings to almost all function calls/build with the babel plugin, stating that the old package will no longer receive updates (point to the new package name)

If you have any other strategies in mind, please share.

**Comment by AlexMost** [comment]
@erickwilder sounds ok, will release patch version with warnings ASAP. I will have more time on this week to finish the transition.

**Comment by AlexMost** [comment]
So, the transition process is almost done:
- [x] published `ttag`, `babel-plugin-ttag`, `ttag-cli` packages with all tests and docs fixes.
- [x] Added some notes about new name migration to projects README's
- [x] created `c-3po-support` branches in repositories for bugfixes to the old name packages.
- [x] Added some fixes to documentation.

Let me know If I have missed something.

@erickwilder thanks for your help :)

Future plans:
1. Create new projects website with documentation on `ttag.js.org`. It can be implemented in a separate repository and `c-3po.js.org` can refer to the new site. https://github.com/ttag-org/ttag/issues/108
2. Think about the logo, I think every project needs that - https://github.com/ttag-org/ttag/issues/109
