### ISSUE TITLE
ttag logo

### ISSUE THREAD

**Issue by AlexMost** [ttag-org/ttag#109]
Here we can discuss projects logo.

> Suggestion from @erickwilder:
https://openclipart.org/detail/293011/tea-bag-in-cactus-cowboy-bold-stroke-icon-style from  this issu e https://github.com/ttag-org/ttag/issues/105#issuecomment-384281745

**Comment by AlexMost** [comment]
https://ttag.js.org/

**Comment by erickwilder** [comment]
![ttag-logo](https://user-images.githubusercontent.com/607262/47254908-6cb09800-d468-11e8-9c8a-27fbc61f92be.png)

I know that this issue was already closed. I had some sketches that (because of lack of time) I didn't share. Here's one of my ideas.
