### ISSUE TITLE
Does it work with react native?

### ISSUE THREAD

**Issue by chrusart** [ttag-org/ttag#114]
I can extract translations, merge .pot to .po, but can't make it work in RN.
Weird thing is that it only works when I debugging remotely in chrome and reading stored json files.
It doesn't work when I'm not connected to remote debugger, it has a problem as stored json files are stripped from Symbol types after JSON.stringify().
```
undefined is not a function (evaluating 'getObjectKeys(translateObj.translations)[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
```

**Comment by chrusart** [comment]
Ok, probably it has something to do with JavaScriptCore as it's outdated in Android.
Symbol is not in shipped in JSC for Android.
https://github.com/facebook/react-native/issues/15902
https://github.com/facebook/react-native/pull/5294#issuecomment-190061913

**Comment by chrusart** [comment]
Ok, with new JSC works.
https://github.com/react-community/jsc-android-buildscripts
Binaries -  ```yarn add jsc-android``` and just setup Andoid project.

**Comment by AlexMost** [comment]
Hey @chrusart, sorry for the late reply.  Thanks for the research - this can be really helpful. Feel free to report any issues or request a feature) Any feedback is appreciated!
