### ISSUE TITLE
Support _() function.

### ISSUE THREAD

**Issue by romaia** [ttag-org/ttag#118]
At a project I am working on, we currently use our own home brew translation infrastructure based on gettext, but we are currently limited by it not handling template literals (as you do nicely).

So, considering a migration plan, I would like to start using ttag without the need to replace all usages of _() for gettext() or t``.

So, given that there is already a gettext() function available, it would be nice if it also supported the standard _() gettext function (maybe optionally to not break projects that use that function for something else).

**Comment by AlexMost** [comment]
ttag supports aliasing - https://ttag.js.org/aliasing.html. Can that fix your issue?

```js
import { gettext as _ } from 'ttag'
_('translation');
```

**Comment by romaia** [comment]
Yes, it does!

Can't believe I missed that in the docs. Thanks.

**Comment by AlexMost** [comment]
great! feel free to ask any questions here)
