### ISSUE TITLE
Support for babel 7

### ISSUE THREAD

**Issue by hackedbellini** [ttag-org/ttag#121]
https://babeljs.io/blog/2018/08/27/7.0.0

**Comment by hackedbellini** [comment]
@AlexMost I think babel-upgrade will do almost everything (if not everything) you need: https://github.com/babel/babel-upgrade

**Comment by AlexMost** [comment]
Seems like all packages are updated to use babel 7. 
You can check this in a pre minor release - `1.3.0-0`. 
Any feedback about bugs or suggestions will be appreciated!

**Comment by hackedbellini** [comment]
@AlexMost awesome! I'll update my dependencies here and test and will report here about any issue that I find!
