### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by AlexMost** [ttag-org/ttag#123]
Since we have migrated to babel 7.x with typescript support, it would be nice to have a doc, describing how we can integrate `ttag` with `typescript`.

**Comment by erickwilder** [comment]
[ ] Add TS `typings` to `ttag` project
[ ] Add TS typings to `ttag-org/babel-plugin-ttag`

I can start with that by adding basic TypeScript support.

**Comment by AlexMost** [comment]
Oh, this ticket is more about translations extraction from the typescript. So, basically what we need is:

- [ ] Ability to extract translations from the ts and tsx files (must work with @babel/preset-typescript)
- [ ] ttag-cli should recognize ts files (for now it works only with js and jsx) https://github.com/ttag-org/ttag-cli/blob/master/src/lib/pathsWalk.ts#L14
- [ ] write little doc about how to use ttag for the ts project.

The questions to discuss:
Should we add `ts` support by default to ttag-cli (with no extra install @babel/prest-typescript for the user)? Or we should put this on the users? We already install @babel/preset-react with cli, so should we do the same for ts?

So, what do you think?

**Comment by erickwilder** [comment]
Sorry, I misunderstood and I started to work on the type definitions. Anyway I got a PR to improve TS types a bit: https://github.com/ttag-org/ttag/pull/129

**Comment by erickwilder** [comment]
> Should we add ts support by default to ttag-cli (with no extra install @babel/prest-typescript for the user)? Or we should put this on the users? We already install @babel/preset-react with cli, so should we do the same for ts?

Since the CLI is a `devDependency` and should not hit any production code I would say that is fine to add TS support on it.

**Comment by AlexMost** [comment]
> Sorry, I misunderstood and I started to work on the type definitions. Anyway I got a PR to improve TS types a bit

Great, thanks!

**Comment by AlexBazer** [comment]
When using ttag-cli with typescript + babel + webpack, **do not forget to update to babel v7**, because on `ttag update` you can get `Plugin/Preset files are not allowed to export objects, only functions.` error

(actually I don't know, maybe this error can happen with babel + webpack too)
