### ISSUE TITLE
documentation for integration with gatsby

### ISSUE THREAD

**Issue by jaredh159** [ttag-org/ttag#133]
Hi there, I really appreciate all the work on ttag, great library.

I spent a chunk of time yesterday and today trying to figure out how to use ttag with gatsby, and found the documentation a bit hard to follow. I wanted to do pre-compilation, but struggled to adapt the directions for CRA, and manual invoking `ttag-cli` from the command line (as indicated in the "Getting Started" section) didn't seem to work with the workflow and opinionated build and develop steps of gatsby.

Anyway, after a fair bit of trial and error, I think I figured out how to put the pieces together, and made a [simple gatsby starter with basic ttag support](https://github.com/jaredh159/gatsby-starter-ttag). I was wondering about a couple things:

* did I do it right in the above-linked repo? is that the correct way to handle build-time precompilation using the babel plugin?
* would it be worth making a section in your docs somewhere about gatsby integration?
* or maybe showing a simple `babel.config.js`  somewhere in the docs like the one I eventually figured out (if it's correct) might be helpful to someone else trying to grok all the moving pieces.

I also [submitted the gatsby starter](https://github.com/gatsbyjs/gatsby/pull/10352) to get it listed on their website, for anyone else coming along hoping to jump start with a a hello-world gatsby + ttag starter, fwiw.

**Comment by jaredh159** [comment]
@AlexMost thanks for the response. I'd be willing to take a crack at adding to the documentation, just wondering if you'd give me a little bit of direction how you'd envision any addition so I don't waste my time. For instance, do you think I should add a "Gatsby" sub-page under the "Getting Started" section, as a sibling to the "Create React App" page?  Or is that overkill -- should I just add a note or callout on another page somewhere?

And then, with respect to the babel.config.js -- where would you envision placing an example config file like I proposed? The places that seem logical to me would either be under the "Precompiled translations" section at the bottom of the "Getting Started" page, or on the babel-plugin-ttag api page.

**Comment by alxpy** [comment]
> As for the Precompiled translations I think we can put it to the Features section.
:ok_hand:
