### ISSUE TITLE
dtslint is failing

### ISSUE THREAD

**Issue by AlexMost** [ttag-org/ttag#136]
Something bad happens with dtslint
https://travis-ci.org/ttag-org/ttag/jobs/466242717

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for typescript@3.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-12-10T22_59_17_742Z-debug.log
    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```
I have updated `CHANGELOG.md` and accidantely touched package-lock.json file. I have reverted those changes but seems like it has no effect on CI.

Not sure where to look at, can you help me with this please @erickwilder ?

**Comment by taion** [comment]
Upgrading from 0.3.0 to 0.4.2 fixed this for me.

**Comment by erickwilder** [comment]
Sorry @AlexMost - I've been busy during the end of the year (the perks of working with e-commerce-related products)

---

Is this still an issue?

**Comment by erickwilder** [comment]
Okay. I did check the latest builds and it still fails. Unfortunately, just upgrading (as suggested by @taion did not solve the issue for me - macOS, node@11.6.0, npm@6.5.0.

I'm still trying to figure it out why is it breaking out of a sudden.
