### ISSUE TITLE
Update errors to refer to ttag instead of c-3po

### ISSUE THREAD

**Issue by dimaqq** [ttag-org/ttag#144]
E.g. https://github.com/ttag-org/ttag/blob/7c4cfc861c0197eb2c5ba74dfbfc08ebaa06ef1e/src/validation.js#L25

When hit, it produces:
```
Unhandled Rejection (Error): 
            Locale data sould contain headers "undefined".
            see - https://c-3po.js.org/configuration-c-3po-lib.html#addlocale-string-locale-object-data-bool-replacevariablesnames
```

And the link is dead ☠️ 

Also there's a typo: `s/sould/should`

**Comment by AlexMost** [comment]
`1.7.1` version with fix is available
