### ISSUE TITLE
Incomplete precompilation output when using context mechanism

### ISSUE THREAD

**Issue by manuel-woelker** [ttag-org/ttag#151]
Hi, first of all thanks for the great lib - much appreciated! However I ran into a bit of an issue today:

When using ttag-cli to precompile translations, the resulting code is malformed.
I put up a simple demo repo here: https://github.com/manuel-woelker/ttag-precompile-context/blob/master/test.x.js
(Run  using `yarn install && yarn run precompile`)
Input (in file test.js):
    
    console.log(c('foo').t`with_context`);

Expected output (in test.x.js, using translation file x.po):

    console.log("two");

Actual output:

    "two";

Interestingly, wrapping the translation part with a bogus function makes it work, e.g.:

    console.log(make_it_work(c('foo').t`with_context`));

My best guess is that the transformation function is somehow removing too much of the AST during the replacement.

It could also reproduce this with the babel-plugin-ttag and babel-plugin-macros.

Any ideas what the issue might be? Thanks in advance!

**Comment by AlexMost** [comment]
Hi @manuel-woelker, glad that you liked our lib. Seems like it's a bug. Going to investigate, will report any progress here.

**Comment by manuel-woelker** [comment]
Thanks for the quick feedback! Let me know if I can support in any way.

**Comment by AlexMost** [comment]
You can try the new version of `ttag-cli@1.7.2` that fixes this issue. Please, let me know if that works.

**Comment by manuel-woelker** [comment]
I just verified with 1.7.2 and it's looking great! Thanks again for the quick fix.
