### ISSUE TITLE
Wrong definition of header in .po file

### ISSUE THREAD

**Issue by mkosir** [ttag-org/ttag#154]
When generating new .po file for example `en` language, `Plural-Forms` in header is defined with JavaScript comparison operators like this:
`"Plural-Forms: nplurals = 2; plural = (n !== 1);\n"`
but it should be like this:
`"Plural-Forms: nplurals=2; plural=n != 1;\n"`

**Comment by AlexMost** [comment]
Hi @mkosir !
It works in a way that it was defined in https://github.com/ttag-org/plural-forms/blob/master/src/catalog.js#L435. Do those extra spaces are breaking your translations?

**Comment by mkosir** [comment]
Yes, if changed it manually from `!==` to `!=` . Also you can try to open it with Poedit, which will give you warnings in first case.
Keep up the good work, I'm still a fan of this library, I get a filling that most of the libraries this days are trying to reinvent the wheel with "json based translation files" which you cant generate from code.

**Comment by AlexMost** [comment]
you can try fix in `1.7.4`.
