### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by anilanar** [ttag-org/ttag#161]
When using `node: false` option in webpack.config, the following error occurs:

```
utils.js:243 Uncaught ReferenceError: process is not defined
    at Object../node_modules/ttag/dist/utils.js (utils.js:243)
```

The line:
```
var isDebug = !(process && process.env.NODE_ENV === 'production');
```

When `node` is false, `process` doesn't exist but webpack can still replace `process.env.NODE_ENV` with `true/false` via `webpack.DefinePlugin`.

**Comment by AlexMost** [comment]
@anilanar Thanks for the report! Seems like it's a bug.

**Comment by AlexMost** [comment]
You can try ` ttag@1.7.9`. This issue should be fixed.
