### ISSUE TITLE
It doesn't load translations with the compact mode

### ISSUE THREAD

**Issue by dhoko** [ttag-org/ttag#169]
Hey :wave: 

I have an issue with the new compact mode, cf https://github.com/ttag-org/ttag/pull/165 it doesn't work for me :/ 

1. Load the app without the compact mode (-> normal mode), everything is fine all translations are ok
2. Load the app with translations using the compact mode, the webapp is not translated :/ 

cf https://codesandbox.io/s/kind-noether-37hr0

**Comment by AlexMost** [comment]
Hi @dhoko! Seems like you have found a bug. The fix is already available in `+ ttag@1.7.14` you can try it. Please, let me know if that works.

**Comment by AlexMost** [comment]
I have tried the new version on your example and seems like it works now - https://codesandbox.io/embed/beautiful-merkle-d0pjn

**Comment by dhoko** [comment]
Yep it works :+1: thx
