### ISSUE TITLE
translator comments in JSX

### ISSUE THREAD

**Issue by benmonro** [ttag-org/ttag#180]
currently the docs here: https://ttag.js.org/docs/translator-comments.html
 do not mention any way to add a translator comment within JSX.

we might have some large blocks of JSX and putting the comment at the top would be kind of awkward, would be nice if we could do the following:

```
<MyComponent>{/* translator: Use this for that thing you want to do */ t`Thing Name`}</MyComponent>
```

is this possible?  and if so can it be added to the docs? :)

**Comment by AlexMost** [comment]
This feature is was disabled by default for some reason. fixed in ttag-cli@1.7.19
