### ISSUE TITLE
Does ttag support ICU message format?

### ISSUE THREAD

**Issue by benmonro** [ttag-org/ttag#181]
wondering if there are plans to support ICU?

**Comment by benmonro** [comment]
https://twitter.com/kentcdodds/status/1157380102893662208?s=20

**Comment by AlexMost** [comment]
That is a good question. ICU seems like a more advanced and feature-rich format. Personally, I don't have any experience with it. I was investigating some time ago, and it looked a little bit complex, that was the reason why we have chosen gettext. But, anyway, I am open to any ideas about how we can start integration with ICU format.

**Comment by eckertalex** [comment]
@AlexMost I think this issue can also be closed?
