### ISSUE TITLE
No translation when identifier resolves to undefined

### ISSUE THREAD

**Issue by glecetre** [ttag-org/ttag#183]
Hello,

We are using ttag on one of our projects and we recently faced an issue with it.
We have a translation key containing a simple identifier. It is correctly translated when the identifier is set, but not when it is undefined.

I reproduced the situation in [this codesandbox](https://codesandbox.io/s/jolly-joliot-zqupf?fontsize=14). You can comment or uncomment line 10 of index.js to see that the translation is OK when commented out, but not when uncommented. "coucou" is the original text and "hi" is the translation.

**Comment by AlexMost** [comment]
Hi @glecetre!
Looked through your example and noticed that you are using `str` for `msgstr`, but it must be `str[]`. `msgstr` must be an array of strings. But seems like you have found a bug with `undefined`. Will take a look closer today. Thanks for the report!

**Comment by glecetre** [comment]
I fixed the snippet following your explaination :)
Thanks for looking into it

**Comment by AlexMost** [comment]
The new version with fix is available - `1.7.18`. Seems like it works https://codesandbox.io/s/beautiful-bird-2vj37. Thanks for the report, let me know if something doesn't work for you!
