### ISSUE TITLE
webpack po loader

### ISSUE THREAD

**Issue by dimaqq** [ttag-org/ttag#205]
Hi `ttag` devs,

I've written a teeny-tiny webpack loader that allows you to `import` PO files directly.
https://github.com/dimaqq/ttag-po-loader

Specifically I thought that running `po2json` manually was an unnecessary step/complication. Now, for example, a translator can edit a PO file and see the changes reflected live in the UI 🕺 (assuming HMR, like `yarn start` for CRA).

I'd love for this to be available to other ttag users, for example it would be awesome if the ttag org took over this loader 😸 

Cheers,
Dima Tisnek

**Comment by AlexMost** [comment]
Hi @dimaqq! Awesome work! If you want we can place this repo in ttag-org also. I have sent you the invitation to ttag-org

**Comment by dimaqq** [comment]
Done 🎉 
May need some help later with cleaning it up enough to be pushed to npm...
