### ISSUE TITLE
Plural for a 0 value

### ISSUE THREAD

**Issue by nico3333fr** [ttag-org/ttag#210]
Hi there,

I'm working with a countdown in JS that uses ttag for translations, and I went across this case:
```js
c('Countdown unit').ngettext(msgid`${seconds} second`, `${seconds} seconds`, seconds)
```

When the number of seconds is 1, I get the singular version, but when the value is 0, I still get the plural version:
![image](https://user-images.githubusercontent.com/2578321/95467270-8c0a9d80-097d-11eb-8753-ce13f96c4828.png)

I went in your doc, and this is the same case in your example (0 ticks):
![image](https://user-images.githubusercontent.com/2578321/95466951-32a26e80-097d-11eb-924b-85f6d2dc83e7.png)

Is it possible to get a singular version when the value equal to 0?

Thanks in advance!

**Comment by AlexMost** [comment]
Hi @nico3333fr! It depends on the active language. `0 seconds` is a valid form for `0` as far as I know, because plural formula for English is simply `n!=1`

**Comment by nico3333fr** [comment]
@AlexMost but is it possible to adapt it depending of the language?

**Comment by AlexMost** [comment]
Yes, for sure. Depending on your case, you can use `useLocale` function - https://ttag.js.org/docs/library-api.html#uselocale to switch language, or `setDefaultLang` https://ttag.js.org/docs/library-api.html#setdefaultlang if you have other than English lang in your sources.
