### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by eckertalex** [ttag-org/ttag#225]
Is this project dead? What are the future plans?

**Comment by AlexMost** [comment]
Hi @eckertalex! What makes you think that this project is dead?

**Comment by eckertalex** [comment]
The age of some of the github issues was suspicious and some issues are still open that should probably be closed (#172). A superficial look at the commit history also seems like there is no active development being done. The last npm version was published 5 months ago. Seemed dead, but could be a sign of a mature library, I guess :)

Anyway, I am happy if this was not abandoned, as I really like this library so far. Is there anything I could help with?

**Comment by AlexMost** [comment]
Glad that you liked the lib! Completely agree, that some issues should be fixed long time ago ( Trying to fix critical ones when I have time. Anyway, this project is not abandoned. I have some ideas on adding more docs for contributors to involve more people in the project development. If you have some issues or idea on how we can make this project better - feel free to create an issue. Thanks for your feedback anyway!

**Comment by eckertalex** [comment]
If you're okay with that, I will start by looking which issues can already be closed and I might look how I can improve documentation for react apps. I am not quite happy how the setup works currently.
Closing this issue since it has been answered. Thanks!

**Comment by AlexMost** [comment]
@eckertalex great, thank you!
