### ISSUE TITLE
jt documentation and type is incorrect

### ISSUE THREAD

**Issue by tlrobinson** [ttag-org/ttag#233]
This documentation

 > The biggest difference between jt and t is that t concatenates translations and expressions all together into a single string, while jt returns an array of the translated strings and expressions that can be used in jsx.

and this TypeScript type

https://github.com/ttag-org/ttag/blob/master/types/index.d.ts#L22

aren't quite right. `jt` returns an array of strings and any template variables.

I think this is a better type:

```
export function jt<T>(strings: TemplateStringsArray, ...expr: T[]): string | (string | T)[];
```

A workaround is to redeclare the type in some TypesScript file in your project:

```
import "ttag";

declare module "ttag" {
  function jt<T>(strings: TemplateStringsArray, ...expr: T[]): string | (string | T)[];
}
```

**Comment by AlexMost** [comment]
good point, this needs to be fixed

**Comment by AlexMost** [comment]
done in `1.8.5` :heavy_check_mark:
