### ISSUE TITLE
Add index.d.ts to root level dir to support typescript auto-import

### ISSUE THREAD

**Issue by sentilesdal** [ttag-org/ttag#238]
Currently the index.d.ts file lives in the types/ directory.  Auto-import for IDEs will then try to import ttag function from 'ttag/types'.  When building this package for npm, the types file should be copied to be a sibling of the main index.js file.

**Comment by piecyk** [comment]
Yes, let's fix it, having `import { t } from 'ttag/types'` as auto import is bad

**Comment by AlexMost** [comment]
done in `1.8.5` :heavy_check_mark:
