### ISSUE TITLE
discover c-3po functions by require

### ISSUE THREAD

**Issue by AlexMost** [ttag-org/ttag#44]
for now c-3po functions are discovered only by imports, but it is also necessary to discover them by require to make everything work on the backend side.

babel-plugin-c-3po should be able to discover this:

```js
const { t } = require('c-3po');
```

**Comment by alxpy** [comment]
it works now!
```js
const { t } = require('c-3po');
console.log(t`test text`);  // test text
```

**Comment by AlexMost** [comment]
@alxpy This works in library because it's valid javascript. But it will not be extracted and resolved by babel plugin.

**Comment by AlexMost** [comment]
@snowwm hey, thanks for using our tool. Going to implement this feature on this week. 
Also created a separate issue for merging options from .babelrc - https://github.com/ttag-org/ttag-cli/issues/38

**Comment by AlexMost** [comment]
Preminor versions with this functionality are available:

```
babel-plugin-ttag@1.1.0-0
ttag-cli@1.1.0-0
```

Feel free to report any issues.
