### ISSUE TITLE
create-react-app integration

### ISSUE THREAD

**Issue by opyh** [ttag-org/ttag#62]
As you asked for suggestions here is one 😅

It would be really cool to have an app template / integration into [create-react-app](https://github.com/facebookincubator/create-react-app).

Thanks to all contributors for this great piece of software!

**Comment by AlexMost** [comment]
Thanks for the suggestion. Good idea, I was also thinking about it. Need some time to look closer at how it can be integrated with create-react-app.

**Comment by MrOrz** [comment]
I am currently thinking how we can use c-3po on next.js projects.

I think I would spin up multiple servers of next.js, compiled with different babel configs with different locales, and have an nginx server to switch between them :P
