### ISSUE TITLE
Context doesn't convert by webpack correctly

### ISSUE THREAD

**Issue by mr-devboy** [ttag-org/ttag#94]
For compairing:
```
// Source file
...
'PPS-d94b19cc-114f-4f44-9cc4-4138e80a87b9_cvv': c('paymentErrors').t`pp_field_cvv`,
unknownError: t`Произошла неизвестная ошибка`,
...

// Wepack bundled file
'PPS-d94b19cc-114f-4f44-9cc4-4138e80a87b9_cvv': Object(__WEBPACK_IMPORTED_MODULE_1_c_3po__["c"])('paymentErrors').t`pp_field_cvv`,
unknownError: Object(__WEBPACK_IMPORTED_MODULE_1_c_3po__["t"])(_templateObject)
```

As you can see, without 'c' all works good. But I need context

**Comment by AlexMost** [comment]
Hi, thanks for your report! 
As far as I see, the problem is that resulting code with `c` is not transpiled and doesn't work in es5 environment?

Contexts are quite new feature, will take a look at this issue ASAP.

**Comment by AlexMost** [comment]
Trying to reproduce your case, can you please provide an example of the webpack configuration which you are using?
