### ISSUE TITLE
xgettext format compatibility

### ISSUE THREAD

**Issue by AlexMost** [ttag-org/ttag#99]
For now, c-3po extracts expressions in `${ expr }` form. There are also some tools that use `{ 0 }` format (xgettext). There is a feature request to implement some kind of compatibility with xgettext - https://github.com/metabase/metabase/issues/6680#issuecomment-369546923 . What do you think? @vharitonsky @MrOrz @alxpy

**Comment by tlrobinson** [comment]
As a workaround I'm just running sed on the `.po` files

```bash
sed -E 's/\$\{ *([0-9]+) *\}/{\1}/g'
```
and reversing it before compiling

```bash
sed -E 's/\{ *([0-9]+) *\}/${ \1 }/g'
```

**Comment by AlexMost** [comment]
https://ttag.js.org/docs/plugin-api.html#confignumberedexpressions
